### ISSUE TITLE
No visibility into the driver's code

### ISSUE THREAD

**Issue by Fordi** [Elecrow-keen/Elecrow-LCD5#1]
Seriously.  I'm not running this unless I know what it does.  Can we get the sources?

**Comment by Elecrow-RD** [comment]
This is a set of output mode of the screen and the touch screen driver on RPI. And i am so sorry that it is not open source. Because it involves trade secrets.Thanks for your attention.

**Comment by ChrisAFRcrew** [comment]
Not working for me and now I know what to do but return the product.

**Comment by xversial** [comment]
Not interested in buying a product like this if I can't see the source code. Rather not install your _trade secret_ malware.
