### ISSUE TITLE
Packages for architectures other than Arm?

### ISSUE THREAD

**Issue by proffalken** [Elecrow-keen/Elecrow-LCD5#3]
Hi,

Whilst I understand that this is primarily aimed at the Pi, is there any chance of getting x86_64 drivers as well?

I'd love to use this as a headless display on a more powerful home cinema device, but at the moment I can't use the touchscreen functionality.

**Comment by Elecrow-RD** [comment]
We are sorry about that the touchscreen driven by gpio ports. So the x86_64 machine can not use it. But you can choice our 7 inch product. it can work on windows perfectly. Amazon link:https://www.amazon.com/Elecrow-Display-Monitor-1024X600-Raspberry/dp/B01GDMDFZA/ref=sr_1_7?m=A3UAI31N6IJM2&s=merchant-items&ie=UTF8&qid=1503891997&sr=1-7
